### ISSUE TITLE
Android 9.0版本小米手机，显示下载成功，但是没有合成和应用

### ISSUE THREAD

**Issue by 64695716** [TinkerPatch/tinkerpatch-sdk#117]
![default](https://user-images.githubusercontent.com/11385942/52775566-f66d1c80-307a-11e9-9736-684cd7f1d6fb.png)

**Comment by beiguancyc** [comment]
我在使用9.0版本的机器上都没有成功。应该是目前不支持9.0吧

**Comment by li-wen-qi** [comment]
我的9.0补丁未生效

**Comment by shouPol** [comment]
将tinker版本换成1.9.9试试

**Comment by simpleton** [comment]
这个的根本问题是Android9.0的小米对于没有自启动权限的APP，禁止使用jobscheduler。

**Comment by zhouzhijiang** [comment]
TINKER_VERSION=1.9.13 TINKERPATCH_VERSION=1.2.12
这个版本目前我试了是可以的

**Comment by simpleton** [comment]
建议使用最新版（1.2.13）
