### ISSUE TITLE
sync response in update

### ISSUE THREAD

**Issue by wyh497823256** [TinkerPatch/tinkerpatch-sdk#13]
12-07 10:37:55.906 28423-28497/? E/Tinker.ClientImpl: tinker server sync respond:{"v":10}
12-07 10:37:55.906 28423-28497/? I/Tinker.ClientImpl: sync response in update:version:10
                                                      grayValue:null
                                                      conditions:
                                                      pause:false
                                                      rollback:false
12-07 10:37:55.916 28423-28497/? W/Tinker.ClientImpl: update return false, target version is not latest. current version is:10
12-07 10:37:55.916 28423-28497/? I/Tinker.ClientImpl: Needn't update, sync response is: version:10
                                                      grayValue:null
                                                      conditions:
                                                      pause:false
                                                      rollback:false
                                                      gray: 1
客户端上一个版本：1.6.4 ,thinker_id :iqc164，补丁版本：10，已删除
当前客户端版本：1.6.5,tinker_id:iqc165 ,补丁版本:0
我现在上传了一个1.6.5版本的补丁，但是请求服务器的补丁版本一直是 1.6.4_v10的补丁包。无法更新到1.6.5_1的版本。

**Comment by wyh497823256** [comment]
忘了说明一点，我的补丁下发模式设置的是开发预览。并且开启了DebugTool的debug模式

**Comment by shwenzhang** [comment]
当前客户端版本：1.6.5,tinker_id:iqc165 ,补丁版本:0  这个已经在服务器新建了么？

**Comment by wyh497823256** [comment]
@shwenzhang 
![image](https://cloud.githubusercontent.com/assets/8830870/20953286/4237593e-bc6d-11e6-93a5-91246442ebae.png)
已经新建了

**Comment by shwenzhang** [comment]
你把日志给一下，加载过程的日志，看看开发模式是否已经生效

**Comment by wyh497823256** [comment]
12-07 10:59:51.476 1139-1139/? D/Tinker.Utils: update value: key=.com.tinker.debugtool.debug, value=true
12-07 10:59:52.476 1139-1139/? W/Tinker.SettingsActivity: set debug newValue:false
12-07 10:59:52.486 1139-1139/? D/Tinker.Utils: update value: key=.com.tinker.debugtool.debug, value=false
12-07 10:59:53.326 1139-1139/? W/Tinker.SettingsActivity: set debug newValue:true
12-07 10:59:53.356 1139-1139/? D/Tinker.Utils: update value: key=.com.tinker.debugtool.debug, value=true
12-07 11:00:00.606 1188-1188/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.wodedagong.app.iqc/tinker
12-07 11:00:00.606 1188-1188/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-07 11:00:00.616 1188-1188/? W/Tinker.Tinker: tinker patch directory: /data/data/com.wodedagong.app.iqc/tinker
12-07 11:00:00.616 1188-1188/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
12-07 11:00:00.626 1188-1188/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
12-07 11:00:00.626 1188-1188/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/com.wodedagong.app.iqc/tinker, code:-2, cost:4
12-07 11:00:00.626 1188-1188/? W/Tinker.Tinker: tinker load fail!
12-07 11:00:01.066 1188-1188/? W/Tinker.Debugger: debugger attached
12-07 11:00:01.066 1188-1188/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
12-07 11:00:01.076 1188-1188/? W/Tinker.ServerManager: installTinkerServer, debug value:true
12-07 11:00:01.116 1188-1188/? I/Tinker.ClientImpl: updateVersionProperty file path:/data/data/com.wodedagong.app.iqc/tinker_server/version.info , appVersion: 1.6.4 , patchVersion:0 , patchMd5: , grayValue:9 , uuid:fd193c4b-99f3-418d-bfed-f362cfb2c174
12-07 11:00:01.126 1188-1188/? D/Tinker.DefaultAppLike: onCreate
12-07 11:00:04.926 28423-28497/? D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
12-07 11:00:04.926 28423-28497/? E/Tinker.ClientImpl: tinker server sync respond:{"v":10}
12-07 11:00:04.936 28423-28497/? I/Tinker.ClientImpl: sync response in update:version:10
                                                      grayValue:null
                                                      conditions:
                                                      pause:false
                                                      rollback:false
12-07 11:00:04.936 28423-28497/? W/Tinker.ClientImpl: update return false, target version is not latest. current version is:10
12-07 11:00:04.936 28423-28497/? I/Tinker.ClientImpl: Needn't update, sync response is: version:10
                                                      grayValue:null
                                                      conditions:
                                                      pause:false
                                                      rollback:false
                                                      gray: 1
@shwenzhang  请看一下，谢谢

**Comment by wyh497823256** [comment]
![image](https://cloud.githubusercontent.com/assets/8830870/20953343/ce34d24a-bc6d-11e6-83c5-416a7c0caf4f.png)

**Comment by shwenzhang** [comment]
12-07 11:00:01.116 1188-1188/? I/Tinker.ClientImpl: updateVersionProperty file path:/data/data/com.wodedagong.app.iqc/tinker_server/version.info , appVersion: 1.6.4 , patchVersion:0 , patchMd5: , grayValue:9 , uuid:fd193c4b-99f3-418d-bfed-f362cfb2c174

**Comment by shwenzhang** [comment]
你确定你的appversion已经改成1.6.5？

**Comment by wyh497823256** [comment]
![image](https://cloud.githubusercontent.com/assets/8830870/20953430/8d790400-bc6e-11e6-96c9-5de5cc68f3b6.png)
这是我从 thinker_server文件夹当中提取出来的。
![image](https://cloud.githubusercontent.com/assets/8830870/20953443/a8931ea6-bc6e-11e6-984a-5dd78ce6bd55.png)
这是我上线的app版本。这是自动读取的。

**Comment by shwenzhang** [comment]
你要新版本代码传入的变成1.6.5

**Comment by wyh497823256** [comment]
@shwenzhang 不好意思，不明白你说的什么意思

**Comment by shwenzhang** [comment]
你QQ找我说把
