### ISSUE TITLE
实时统计存在数据重叠的问题

### ISSUE THREAD

**Issue by wyh497823256** [TinkerPatch/tinkerpatch-sdk#14]
![image](https://cloud.githubusercontent.com/assets/8830870/21339096/2f29d7f0-c6b7-11e6-8716-e75f79544060.png)
数据统计 成功 和失败数量应该存在重叠问题，当前数据已经超过了我的用户数

**Comment by simpleton** [comment]
嗯，对的，以前的失败统计是只要失败一次就会上报。有可能前面失败了，重试又成功了，随意会出现这种情况。正在更新一版sdk，下个版本会fix这个问题。
多谢提出issue。

**Comment by simpleton** [comment]
在新版本`com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.0.1`,优化了上报。区分了下载成功和合成成功。
