### ISSUE TITLE
tinkerpatch 成功安装了两个patch包，统计的数量是0

### ISSUE THREAD

**Issue by small-tree** [TinkerPatch/tinkerpatch-sdk#17]
http://tinkerpatch.com 上统计的成功数是0，过滤log看到一个错误Failed to find provider info for com.tinker.debug.debugprovider，不知道跟着错误有没有关习
版本 com.tencent.tinker:tinker-server-android:0.3.2

**Comment by simpleton** [comment]
@small-tree 这个只是debug tools的log，没有关系的。你使用的是什么版本的sdk的呢？

**Comment by simpleton** [comment]
@small-tree 你可以过滤一下`Tinker.ClientImpl`这个TAG的log, 看是否有`reportSuccess successfully:` 或者 `reportSuccess error`的log.

**Comment by small-tree** [comment]
成功下载统计到了，成功应用数量没有统计到

01-05 11:57:19.966 11335-11706/? W/Tinker.ClientImpl: update return true, patchVersion from 0 to 15
01-05 11:57:19.966 11335-11706/? W/Tinker.ClientImpl: isInGrayGroup return true, gray value:null and my gray value is 3
01-05 11:57:20.086 11335-11706/? I/Tinker.ClientImpl: updateVersionProperty file path:/data/user/0/com.minxindai/tinker_server/version.info , appVersion: 4.5.8 , patchVersion:15 , patchMd5:f03c1c258c1007a5780bb3617918981c , grayValue:3 , uuid:937df269-d284-4f36-9c3d-e30055637462
01-05 11:57:20.356 11335-11706/? D/Tinker.ClientImpl: reportSuccess successfully:{"succ":1}

**Comment by small-tree** [comment]
上线比较紧急 - -换了sdk 还要在测试一遍

**Comment by small-tree** [comment]
Tinker.TinkerServerDefaultRequestCallback  log过滤不出来东西

**Comment by simpleton** [comment]
@small-tree 成功应用是在0.3.4+之后增加的上报，0.3.2暂时没有这个上报。你可以重载相关函数，上报到自己的上报系统。
