### ISSUE TITLE
补丁下发失败

### ISSUE THREAD

**Issue by qq634421026** [TinkerPatch/tinkerpatch-sdk#18]
有的时候可以下发 有的时候不可以下发 请问 打基础包盒 差异包 apk文件名字之类的需要注意什么呢

**Comment by simpleton** [comment]
这个应该没有什么限制，可以看下相关log访问的url。另外需要留一下，选择了开发预览，就只能安装过http://tinkerpatch.com/Index/sdk 这个工具，并打开开关才能拉取到。

**Comment by qq634421026** [comment]
我选择的是全量下发 怎么看访问过得url 还有就是这个下发之后是立即生效 还是说 有一点延迟

**Comment by simpleton** [comment]
可以在log中查看。
这个是靠客户端主动拉取的，这个由你本身的代码来控制，sample中的`TinkerPatch.with().fetchPatchUpdate(false);`来控制，false默认是有3小时的间隔的。debug的时候可以改成true，这样每次进程启动都会拉取。

这里还有[开发调试的文档](http://tinkerpatch.com/Docs/dev)，建议还是使用开发预览来做debug。
