### ISSUE TITLE
合成补丁时异常，错误码 -2

### ISSUE THREAD

**Issue by Heart2009** [TinkerPatch/tinkerpatch-sdk#19]
合成补丁时异常，错误码 -2，请问是什么原因引起的，发生类次的异常我们有办法定位具体原因吗？

**Comment by simpleton** [comment]
麻烦提供一下具体的log吧

**Comment by Heart2009** [comment]
线上的版本，没有log

**Comment by Heart2009** [comment]
线上的补丁，没有log哦
![image](https://cloud.githubusercontent.com/assets/6386668/21884955/837ef83a-d8f0-11e6-9df8-c2b59eb70daf.png)
这个成功数跟总数代表什么意思？补丁合成失败数 正好是这两个的差值

**Comment by simpleton** [comment]
@Heart2009 不好意思，下午的飞机所以回复晚了。

成功数就是补丁成功运行，总数为下载了补丁的客户端数。

-2 是 补丁合成异常。这个具体的错误得查到log才能判断。我后续和tinker维护的邵文同学讨论下，因为他们最近也在准备发布1.7.7，我相信是修复了某些特定机型的问题的。

因为log的收集还是个挺敏感的事情，并且存储的成本也较大。这块我看有什么办法只收集tinkerPatch这边的错误log.

**Comment by Heart2009** [comment]
@simpleton 没事，只是有些疑问

![image](https://cloud.githubusercontent.com/assets/6386668/21916601/b44ed642-d97c-11e6-9699-d3cc0d75bc0d.png)
![image](https://cloud.githubusercontent.com/assets/6386668/21916584/a437c110-d97c-11e6-8f44-c85510bd4e3c.png)

从上面两组数据来看，下面那幅图中的运行成功数才是真正的成功数吧，上面那个感觉只是下载成功的个数，但是失败的统计数据是上面那幅图中两个数的差值，该差值感觉更像是下载失败的数目，是不是不太明确呢。。是统计的有问题。。还是我理解的有问题呢。。。

**Comment by simpleton** [comment]
@Heart2009 不好意思，昨晚没有看的特别仔细。
图1的数据 是（下载成功数/下载成功数+失败数）
图2是 （应用成功数/下载成功数）

这块本来都想改成图2的逻辑，应该在后台有遗漏。
PS:你觉得下载成功数的统计（图1）对你是否有价值呢？

**Comment by Heart2009** [comment]
图1价值其实不是很大，主要是图2的数据；
所以图2实时统计中失败的统计是下载失败的数目了（目前从上面截图来看）？

**Comment by simpleton** [comment]
@Heart2009 可以尝试一下新版本，1.1.0。基于tinker 1.7.7开发的，修复了微信在发布1.7.6时遇到的若干问题。
