### ISSUE TITLE
一部华为的手机，合成补丁成功后，又循环输入如下日志，型号是ALE-TL00，系统是EMUI3.1基于Android5.0，tinkerpatch版本是1.0.2，tinker版本是1.7.6

### ISSUE THREAD

**Issue by fenghebaiyang** [TinkerPatch/tinkerpatch-sdk#20]
01-13 11:51:48.164 13086-13086/? I/Tinker.ServerUtils: with app key from manifest appKey:53d1f23ff386bc3c
01-13 11:51:48.174 13086-13086/? I/Tinker.ServerUtils: with app version from manifest appVersion:2016122101
01-13 11:51:48.174 13086-13086/? I/Tinker.VersionInfo: readVersionInfo file path:/data/data/com.yunshanghui.o2o/tinker_server/version.info, appVersion: 2016122101, uuid:25adc1d7-ee5d-4933-abc7-ee6228bb1491, abi:armeabi, patchVersion:2, patchMd5:524e105f2472db7e849cce3ce73dcb4b, grayValue:1, crashTimes:0, retryTimes:0
01-13 11:51:48.184 13086-13086/? W/Tinker.Debugger: debugger not attached cu == null
01-13 11:51:48.184 13086-13086/? W/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 2016122101, appKey: 53d1f23ff386bc3c
01-13 11:51:48.194 13086-13086/? W/Tinker.Tinker: tinker patch directory: /data/data/com.yunshanghui.o2o/tinker
01-13 11:51:48.204 13086-13086/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
01-13 11:51:48.204 13086-13086/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:524e105f2472db7e849cce3ce73dcb4b, newVersion:524e105f2472db7e849cce3ce73dcb4b, current:524e105f2472db7e849cce3ce73dcb4b
01-13 11:51:48.204 13086-13086/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
01-13 11:51:48.204 13086-13086/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.yunshanghui.o2o/tinker, code:0, cost:81
01-13 11:51:50.204 13190-13190/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-13 11:51:50.214 13190-13190/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.yunshanghui.o2o:channel count:1
01-13 11:51:50.234 13190-13190/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yunshanghui.o2o-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunshanghui.o2o-1/lib/arm, /vendor/lib, /system/lib]]]
01-13 11:51:50.244 13190-13190/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.yunshanghui.o2o/tinker/patch-524e105f/dex/classes.dex.jar", zip file "/data/data/com.yunshanghui.o2o/tinker/patch-524e105f/dex/test.dex.jar", zip file "/data/app/com.yunshanghui.o2o-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunshanghui.o2o-1/lib/arm, /vendor/lib, /system/lib]]], dex size:2
01-13 11:51:50.244 13190-13190/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
01-13 11:51:50.244 13190-13190/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
01-13 11:51:50.304 13190-13190/? I/Tinker.ServerUtils: with app key from manifest appKey:53d1f23ff386bc3c
01-13 11:51:50.304 13190-13190/? I/Tinker.ServerUtils: with app version from manifest appVersion:2016122101
01-13 11:51:50.304 13190-13190/? I/Tinker.VersionInfo: readVersionInfo file path:/data/data/com.yunshanghui.o2o/tinker_server/version.info, appVersion: 2016122101, uuid:25adc1d7-ee5d-4933-abc7-ee6228bb1491, abi:armeabi, patchVersion:2, patchMd5:524e105f2472db7e849cce3ce73dcb4b, grayValue:1, crashTimes:0, retryTimes:0
01-13 11:51:50.314 13190-13190/? W/Tinker.Debugger: debugger not attached cu == null
01-13 11:51:50.314 13190-13190/? W/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 2016122101, appKey: 53d1f23ff386bc3c
01-13 11:51:50.324 13190-13190/? W/Tinker.Tinker: tinker patch directory: /data/data/com.yunshanghui.o2o/tinker
01-13 11:51:50.334 13190-13190/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
01-13 11:51:50.334 13190-13190/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:524e105f2472db7e849cce3ce73dcb4b, newVersion:524e105f2472db7e849cce3ce73dcb4b, current:524e105f2472db7e849cce3ce73dcb4b
01-13 11:51:50.334 13190-13190/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
01-13 11:51:50.334 13190-13190/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.yunshanghui.o2o/tinker, code:0, cost:72
01-13 11:51:52.044 13252-13252/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-13 11:51:52.054 13252-13252/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.yunshanghui.o2o:channel count:1
01-13 11:51:52.094 13252-13252/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yunshanghui.o2o-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunshanghui.o2o-1/lib/arm, /vendor/lib, /system/lib]]]
01-13 11:51:52.104 13252-13252/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.yunshanghui.o2o/tinker/patch-524e105f/dex/classes.dex.jar", zip file "/data/data/com.yunshanghui.o2o/tinker/patch-524e105f/dex/test.dex.jar", zip file "/data/app/com.yunshanghui.o2o-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunshanghui.o2o-1/lib/arm, /vendor/lib, /system/lib]]], dex size:2
01-13 11:51:52.104 13252-13252/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
01-13 11:51:52.104 13252-13252/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
01-13 11:51:52.164 13252-13252/? I/Tinker.ServerUtils: with app key from manifest appKey:53d1f23ff386bc3c
01-13 11:51:52.164 13252-13252/? I/Tinker.ServerUtils: with app version from manifest appVersion:2016122101
01-13 11:51:52.174 13252-13252/? I/Tinker.VersionInfo: readVersionInfo file path:/data/data/com.yunshanghui.o2o/tinker_server/version.info, appVersion: 2016122101, uuid:25adc1d7-ee5d-4933-abc7-ee6228bb1491, abi:armeabi, patchVersion:2, patchMd5:524e105f2472db7e849cce3ce73dcb4b, grayValue:1, crashTimes:0, retryTimes:0
01-13 11:51:52.174 13252-13252/? W/Tinker.Debugger: debugger not attached cu == null
01-13 11:51:52.184 13252-13252/? W/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 2016122101, appKey: 53d1f23ff386bc3c
01-13 11:51:52.184 13252-13252/? W/Tinker.Tinker: tinker patch directory: /data/data/com.yunshanghui.o2o/tinker
01-13 11:51:52.194 13252-13252/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
01-13 11:51:52.194 13252-13252/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:524e105f2472db7e849cce3ce73dcb4b, newVersion:524e105f2472db7e849cce3ce73dcb4b, current:524e105f2472db7e849cce3ce73dcb4b
01-13 11:51:52.194 13252-13252/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
01-13 11:51:52.194 13252-13252/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.yunshanghui.o2o/tinker, code:0, cost:89
01-13 11:51:53.974 13314-13314/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-13 11:51:53.974 13314-13314/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.yunshanghui.o2o:channel count:1
01-13 11:51:54.074 13314-13314/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yunshanghui.o2o-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunshanghui.o2o-1/lib/arm, /vendor/lib, /system/lib]]]
01-13 11:51:54.084 13314-13314/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.yunshanghui.o2o/tinker/patch-524e105f/dex/classes.dex.jar", zip file "/data/data/com.yunshanghui.o2o/tinker/patch-524e105f/dex/test.dex.jar", zip file "/data/app/com.yunshanghui.o2o-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunshanghui.o2o-1/lib/arm, /vendor/lib, /system/lib]]], dex size:2
01-13 11:51:54.084 13314-13314/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
01-13 11:51:54.084 13314-13314/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
01-13 11:51:54.154 13314-13314/? I/Tinker.ServerUtils: with app key from manifest appKey:53d1f23ff386bc3c
01-13 11:51:54.154 13314-13314/? I/Tinker.ServerUtils: with app version from manifest appVersion:2016122101

**Comment by simpleton** [comment]
收到，我排查一下问题。

**Comment by simpleton** [comment]
@fenghebaiyang 可否把所有的过滤器都关闭，再帮忙抓一份完整的log么？

**Comment by fenghebaiyang** [comment]
尝试重现了3次，没有发现这个问题了。

**Comment by simpleton** [comment]
据我了解微信在灰度Tinker 1.7.6的时候也发现了一些问题，他们正在准备发布1.7.7来fix。我也会第一时间跟进，我会在更新后 close这个issue，也麻烦更新一下sdk.

**Comment by simpleton** [comment]
@fenghebaiyang 可以尝试`tinkerPatch 1.1.0`(base on tinker 1.7.7)。
