### ISSUE TITLE
Can't find AppVersion

### ISSUE THREAD

**Issue by 1019272778** [TinkerPatch/tinkerpatch-sdk#21]
各位大神求助，引入tinker后工程编译时
Error:Execution failed for task ':app:processDefaultConfigDebugManifest'.

Can't find AppVersion in your config, is there match variantName in tinkerpatchSupport config?

tinker version 1.1.0

tinkerpatchSupport {
/** 可以在debug的时候关闭 tinkerPatch **/
tinkerEnable = true
reflectApplication = true
appKey = "1782400ad784c933"
autoBackupApkPath = "${bakPath}"

baseApkInfos {
    item {
        variantName = "debug"
        appVersion = "1.0.0"

        def pathPrefix = "${bakPath}/${baseInfo}/${variantName}/"
        def name = "${project.name}-${variantName}"
        baseApkFile = "${pathPrefix}/${name}.apk"
        baseProguardMappingFile = "${pathPrefix}/${name}-mapping.txt"
        baseResourceRFile = "${pathPrefix}/${name}-R.txt"
    }
    item {
        variantName = "release"
        appVersion = "1.0.0"

        def pathPrefix = "${bakPath}/${baseInfo}/${variantName}/"
        def name = "${project.name}-${variantName}"
        baseApkFile = "${pathPrefix}/${name}.apk"
        baseProguardMappingFile = "${pathPrefix}/${name}-mapping.txt"
        baseResourceRFile = "${pathPrefix}/${name}-R.txt"
    }
}

**Comment by simpleton** [comment]
@1019272778 这块听取了几位用户的意见，大家感觉variantName比较疑惑。所以我重构了一下这块的逻辑。并兼容了老版本的格式，你可以参考一下更新后的文档和sample。对你造成困扰十分抱歉哈。
