### ISSUE TITLE
如果Task为assemble渠道名 同时打出来的debug和release包isRelease()方法无法匹配

### ISSUE THREAD

**Issue by Yuphee** [TinkerPatch/tinkerpatch-sdk#31]

**Comment by simpleton** [comment]
isRelease()只是给大家一个示例，各人还是推荐本地关闭，在ci系统针对不同的task使用环境变量来传递。
assemblen[渠道名] 这种方法已经无法区分buildType，所以无法work。因为tinker的enable是一个全局开关，在不改造plugin的前提下很难针对每个task做适配。

**Comment by Yuphee** [comment]
清楚了
