### ISSUE TITLE
锁屏开始加载补丁，然后，过一会儿点亮屏幕，程序黑屏（预览模式下）

### ISSUE THREAD

**Issue by jiuwu0905** [TinkerPatch/tinkerpatch-sdk#32]
03-06 16:22:29.947 12533-12533/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
03-06 16:22:29.967 12533-12533/? D/Tinker.DefaultAppLike: onBaseContextAttached:
03-06 16:22:29.977 12533-12533/? D/Tinker.DefaultAppLike: onCreate
03-06 16:22:29.997 12533-12533/? I/Tinker.ServerUtils: with app key from manifest appKey:0835895919045178
03-06 16:22:30.007 12533-12533/? I/Tinker.ServerUtils: with app version from manifest appVersion:V4.0.0Grey1062
03-06 16:22:30.007 12533-12533/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.jumper.fhrinstruments/tinker_server/0835895919045178_version.info, appVersion: V4.0.0Grey1062, uuid:80808c74-a180-4f39-bf99-a2f98062c07b, abi:armeabi-v7a, patchVersion:2, patchMd5:afc4e2a08522dc146ac326b0c370bb59, grayValue:1, crashTimes:0, retryTimes:0
03-06 16:22:30.027 12533-12533/? I/Tinker.Debugger: debugger attached
03-06 16:22:30.027 12533-12533/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
03-06 16:22:30.027 12533-12533/? I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: V4.0.0Grey1062, appKey: 0835895919045178
03-06 16:22:30.037 12533-12533/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.jumper.fhrinstruments/tinker
03-06 16:22:30.047 12533-12533/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
03-06 16:22:30.047 12533-12533/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, systemOTA:false
03-06 16:22:30.047 12533-12533/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:afc4e2a08522dc146ac326b0c370bb59, newVersion:afc4e2a08522dc146ac326b0c370bb59, current:afc4e2a08522dc146ac326b0c370bb59
03-06 16:22:30.047 12533-12533/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
03-06 16:22:30.047 12533-12533/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.jumper.fhrinstruments/tinker, code:0, cost:172
03-06 16:22:30.047 12533-12533/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.1.4
03-06 16:22:30.177 12533-12533/? D/Tinker.DefaultAppLike: onTrimMemory level:5
03-06 16:22:30.437 12533-12533/? D/Tinker.DefaultAppLike: onTrimMemory level:80
03-06 16:22:30.557 12533-12533/? D/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-06 16:22:31.267 1430-3260/? I/ActivityManager: Force stopping com.tinker.debug.DebugToolApplication appid=10525 user=0: from pid 3683by app
03-06 16:22:31.267 1430-3260/? I/ActivityManager: Killing 11830:com.tinker.debug.DebugToolApplication/u0a525 (adj 0): stop com.tinker.debug.DebugToolApplicationfrom pid 3683by app
03-06 16:22:31.297 1430-3260/? I/ActivityManager: collectReceiverComponents for intent: Intent { act=android.intent.action.PACKAGE_RESTARTED dat=package:com.tinker.debug.DebugToolApplication flg=0x10 (has extras) }, receivers: null

**然后，一直放着不动，等会就提示 我的程序无效应（ANR）,等待还是关闭

然后关闭应用，再重新开启应用，这时Patch 加载成功，并生效。不会出问题 。。**

手机：
一部华为 honor 7i  ATH-TL00H
一部努比亚 nubia z7 mini   
都是同样的效果。。
我现在再试试全量下发。。

**Comment by shwenzhang** [comment]
你把完整日志给一下把，不要只过滤tinker。系统的日志也要，应该是你接入出现问题

**Comment by jiuwu0905** [comment]
查到原因了，是程序被kill 掉，被系统再次拉起后，出现了一些问题 。
已解决。
目前使用正常。。

**Comment by simpleton** [comment]
好的，有问题再反馈。
