### ISSUE TITLE
TinkerPatch 后端截断 version 导致 404

### ISSUE THREAD

**Issue by DreaminginCodeZH** [TinkerPatch/tinkerpatch-sdk#33]
我在 log 中看到请求的地址是 http://q.tinkerpatch.com/dev/c2e0bbf76178d909/1.0.0-alpha.1%40f7345d6_armv7?d=0cb6d8c9-8820-4c6f-8f4b-08c7a4fb4c6b&v=1489039486847 ，所以 version 应该是 `1.0.0-alpha.1@f7345d6_armv7`；可是在后台添加这个名字的时候发现被截断成了 `1.0.0-alpha.1@f7345d`（而且没有警告），并且替换成这个后访问 URL 则没有问题。

我觉得后端没必要限制 version 的长度（至少没必要这么小，255 字符之类的比较可靠），这样开发者也可以有足够多的信息来区分版本。希望您能够修复这个问题。

**Comment by simpleton** [comment]
已fix，一开始觉得version不会起那么长。

**Comment by shwenzhang** [comment]
限定32个字符，如果超过的话，弹toast？

**Comment by DreaminginCodeZH** [comment]
嗯，以及在网站上也提示下而不要静默截断
