### ISSUE TITLE
这demo

### ISSUE THREAD

**Issue by hiliving** [TinkerPatch/tinkerpatch-sdk#35]

**Comment by simpleton** [comment]
@hiliving 你可以参照一下，https://github.com/TinkerPatch/tinkerpatch-easy-sample
这个使用反射来达到一键接入的目的。

**Comment by hiliving** [comment]
@simpleton 多谢，已经跑通了，之前不清楚要不要先配tinker

**Comment by simpleton** [comment]
不客气，有什么问题可以再咨询
