### ISSUE TITLE
TinkerPatch是不是不支持第三方加固的APP？

### ISSUE THREAD

**Issue by afinal** [TinkerPatch/tinkerpatch-sdk#38]
如果我既想加固APP，又想整合TinkerPatch，有什么解决方案呢？如果我使用1.7.5版本的tinker可以吗？

**Comment by shwenzhang** [comment]
需要等下一个版本会支持加固

**Comment by afinal** [comment]
好的，真是个好消息，可不可以透露一下你们是怎么做这个支持？

**Comment by afinal** [comment]
请问一下，如果我在tinkerpatch.gradle加上usePreGeneratedPatchDex = true是不是也就可以实现加固热修复了？

**Comment by simpleton** [comment]
@afinal 不是的，暂时的版本还不能支持加固。支持加固的版本正在开发中。1.7.5的版本是可以支持加固，但是因为有一些问题，后来那种支持方法被放弃了。

**Comment by afinal** [comment]
@simpleton 好的，谢谢回复，我在代码中加了那行，然后就编译报错了，看来果真如你所说
![image](https://cloud.githubusercontent.com/assets/9390854/24546992/57eedc84-1640-11e7-82d2-abf7a6d9a9a4.png)

**Comment by simpleton** [comment]
@afinal 1.1.5已支持.

**Comment by afinal** [comment]
谢谢你的回复。
