### ISSUE TITLE
构建补丁包的问题

### ISSUE THREAD

**Issue by xia0713** [TinkerPatch/tinkerpatch-sdk#42]
在使用TinkerPatch时，看到文档中有个这步骤：

1.运行 assembleRelease task 构建基准包（请在发布前确保更新tinkerpatchSupport中的appVersion），tinkerPatch会基于你填入的autoBackupApkPath自动备份基础包信息到相应的文件夹，包含：apk文件、R.txt文件和mapping.txt文件 （注：mapping.txt是proguard的产物，如果你没有开启proguard则不会有这个文件）
2.若想发布补丁包， 只需将自动保存下来的文件分别填到tinkerpatchSupport中的baseApkFile、baseProguardMappingFile和baseResourceRFile 参数中；
3.运行 tinkerPatchRelease task 构建补丁包，补丁包将位于 build/outputs/tinkerPatch下。

请问第三步中 “运行 tinkerPatchRelease task” 该怎么运行？与第一步中的 “运行 assembleRelease task” 有什么区别吗

**Comment by simpleton** [comment]
@xia0713 抱歉，前面休假回复晚了。 这里`tinkerPatchRelease`和`assembleRelease` 都是gradle的task。 可以再as中找到相应的task点击执行，或者在命令行中运行`./gradlew [taskName]`

**Comment by xia0713** [comment]
运行好了，但是我把补丁包上传全量发布后，有bug的版本还是没有被修复。该怎么做呀

**Comment by simpleton** [comment]
这个具体需要查看log才能确定是什么问题。可以参照[tinker issue](
https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#issue%E6%8F%90%E9%97%AE%E9%A1%BB%E7%9F%A5)
来提issue.

或者也可以添加qq: 258699730来直接联系我。
