### ISSUE TITLE
com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult

### ISSUE THREAD

**Issue by ding33211** [TinkerPatch/tinkerpatch-sdk#44]
异常类型：com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult

手机型号：OPPO R11

手机系统版本：Android 7.1.1

tinker版本：latest

gradle版本：3.3

是否使用热更新SDK：TinkerPatch SDK

系统：Mac

堆栈/日志：
![image](https://user-images.githubusercontent.com/8023129/30059238-d94c094e-9270-11e7-90f3-f685c5484020.png)

**Comment by ding33211** [comment]
https://github.com/Tencent/tinker/issues/591

**Comment by simpleton** [comment]
@ding33211 麻烦问下使用的是什么版本？

**Comment by ding33211** [comment]
@simpleton 使用的是当前最新版本 1.1.8

**Comment by simpleton** [comment]
是否必先么？可否贴一下相关配置？

**Comment by ding33211** [comment]
必现，目前来看，在上面的tinker issue链接，也有同仁遇到了一样的问题

**Comment by ding33211** [comment]
@simpleton 

```
project    build.gradle

dependencies {
        classpath 'com.android.tools.build:gradle:' + project.ANDROID_GRADLE_TOOL_VERSION
        ...

        // TinkerPatch 插件
        classpath "com.tinkerpatch.sdk:tinkerpatch-gradle-plugin:1.1.8"
}

module  build.gradle
//tinker patch 热修复相关
apply from: 'tinkerpatch.gradle'

dependencies {
    compile fileTree(include: '*.jar', dir: 'src/main/jniLibs')
    ...
    // 热修复 tinker
    compile 'com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.1.8'
}
```

就是按照说明配置来的

**Comment by simpleton** [comment]
不是这个配置，是tinkerpatchsupport的，你的sample可以跑通么？

**Comment by simpleton** [comment]
那个很早就close了，是因为1.0.0的版本的一键接入在Android N上有问题

**Comment by ding33211** [comment]
后面有tinkerpatchsupport的，你看下是由什么问题么

**Comment by simpleton** [comment]
@ding33211 从配置上看没有错误，这个错误是指在oppo r11这一款机器必现么？可否把你的基础包发我邮箱，我debug一下。

PS:可否麻烦您尝试一下sample是否也会出现问题

**Comment by ding33211** [comment]
这边没有OPPO r11的手机，从bugly上来看是必现，每天都稳定提供崩溃
![image](https://user-images.githubusercontent.com/8023129/30144349-3bd0e146-93bd-11e7-9659-512214b859a4.png)

**Comment by ding33211** [comment]
@simpleton 基础包已经发到你邮箱，可以看下
