### ISSUE TITLE
哪里设置patch dir呢

### ISSUE THREAD

**Issue by NickTet** [TinkerPatch/tinkerpatch-sdk#45]
09-15 10:20:58.329 16703-16703/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.ewzj.bigdata/tinker
09-15 10:20:58.330 16703-16703/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-15 10:20:58.331 16703-16703/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.ewzj.bigdata.app.config.BaseApplication
09-15 10:20:58.342 16703-16703/? W/System.err:     at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.a(SourceFile:217)
09-15 10:20:58.342 16703-16703/? W/System.err:     at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.attachBaseContext(SourceFile:81)
09-15 10:20:58.343 16703-16703/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
09-15 10:20:58.350 16703-16703/? D/Tinker.DefaultAppLike: onCreate
09-15 10:20:58.555 16703-16703/? I/Tinker.ServerUtils: with app key from manifest appKey:9de7b9401060a1d0
09-15 10:20:58.555 16703-16703/? I/Tinker.ServerUtils: with app version from manifest appVersion:2.1.9
09-15 10:20:58.557 16703-16703/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.ewzj.bigdata/tinker_server/9de7b9401060a1d0_version.info, appVersion: 2.1.9, uuid:ed0ad231-0543-450b-87b5-a173173f5c14, abi:armeabi-v7a, patchVersion:0, patchMd5:, grayValue:9, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
09-15 10:20:58.565 16703-16703/? I/Tinker.Debugger: debugger attached
09-15 10:20:58.566 16703-16703/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
09-15 10:20:58.566 16703-16703/? I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 2.1.9, appKey: 9de7b9401060a1d0
09-15 10:20:58.569 16703-16703/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.ewzj.bigdata/tinker
09-15 10:20:58.569 16703-16703/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
09-15 10:20:58.569 16703-16703/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.ewzj.bigdata, main process:true, systemOTA:false, fingerPrint:OnePlus/OnePlus3/OnePlus3:6.0.1/MMB29M/386990:user/release-keys, oatDir:null, useInterpretMode:false
09-15 10:20:58.569 16703-16703/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
09-15 10:20:58.570 16703-16703/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.ewzj.bigdata/tinker, code: -2, cost: 2ms
09-15 10:20:58.570 16703-16703/? W/Tinker.Tinker: tinker load fail!
09-15 10:20:58.570 16703-16703/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.1.8
09-15 10:20:58.721 16723-16723/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.ewzj.bigdata/tinker
09-15 10:20:58.721 16723-16723/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-15 10:20:58.722 16723-16723/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.ewzj.bigdata.app.config.BaseApplication

**Comment by simpleton** [comment]
这个不需要设置的，只不过首次加载会因为没有patch而打印出这个log。后续上传patch后即可成功
