### ISSUE TITLE
第一次更新成功后，然后我在新的release包基础上又打新的差分包，然后patch的时候报这个错

### ISSUE THREAD

**Issue by NickTet** [TinkerPatch/tinkerpatch-sdk#46]
Tinker.ReportUtil: checkTinkerApplySuccess, current patch md5:d84a59890c0e03f235c4067d9dd0a159 is not equal with tinker version 8351467ee02024bc53c13df50d61799a

**Comment by simpleton** [comment]
都要基于基础包做patch
