### ISSUE TITLE
project replace KotLin code has question

### ISSUE THREAD

**Issue by kinzirva** [TinkerPatch/tinkerpatch-sdk#47]
![image](https://user-images.githubusercontent.com/11918573/30999801-e33cc982-a49c-11e7-9fa4-3f5f352a5314.png)
我放到java代码的项目里面不会有这个问题 ，补丁还成功
kotlin的项目就这样了！是kotlin jar包不兼容的问题导致diff算法有问题么？麻烦处理下

**Comment by kinzirva** [comment]
dexmode 设置的也没问题 是“jar”

**Comment by kinzirva** [comment]
tinker如果支持kotlin，那么gradle的task可能需要自己重写。怎么个重写法？哪些地方需要重写？

**Comment by simpleton** [comment]
@kinzirva 麻烦问下你使用的build-tools的版本和kotlin runtime的版本？

**Comment by kinzirva** [comment]
问题解决了，开发人员gradle classpath依赖的版本修改了！导致跟tinker android lib的版本绝对不一样。

**Comment by kinzirva** [comment]
麻烦你们了哈
