### ISSUE TITLE
你好，请问如何确认补丁包有被下载成功的?

### ISSUE THREAD

**Issue by minj2me** [TinkerPatch/tinkerpatch-sdk#48]
我查下后台，下载量一直为0的。谢谢

**Comment by minj2me** [comment]
在tinkerpatch-support里， appVersion = "1.0.1"，在app里versionName "1.0"，这样应该没问题的吧?
后台补丁信息：
补丁详情
App版本号：1.0.1
当前补丁版本号：3
当前补丁大小：2.38KB
更新时间：2017-09-30 17:26:00

**Comment by simpleton** [comment]
app version要一致

**Comment by minj2me** [comment]
你好，tinkerpatch-support里的appVersion = "1.0.1"要与补丁详情的 App版本号：1.0.1一致吧？ 现在这两个是一致的，但补丁都没有被更新

**Comment by simpleton** [comment]
查看一下具体log吧
