### ISSUE TITLE
android.system.ErrnoException     android_getaddrinfo failed: EACCES (Permission denied) com.tinkerpatch.sdk.server.b.a$a.run(SourceFile:119)

### ISSUE THREAD

**Issue by ding33211** [TinkerPatch/tinkerpatch-sdk#49]
1 java.lang.SecurityException:Permission denied (missing INTERNET permission?)
--
2 java.net.InetAddress.lookupHostByName(InetAddress.java:471)
3 ......
4 Caused by:
5 android.system.ErrnoException:android_getaddrinfo failed: EACCES (Permission denied)
6 libcore.io.Posix.android_getaddrinfo(Native Method)
7 libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
8 java.net.InetAddress.lookupHostByName(InetAddress.java:445)
9 java.net.InetAddress.getAllByNameImpl(InetAddress.java:259)
10 java.net.InetAddress.getAllByName(InetAddress.java:221)
11 com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
12 com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:233)
13 com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:125)
14 com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:277)
15 com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:215)
16 com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:391)
17 com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
18 com.tinkerpatch.sdk.server.b.a$a.run(SourceFile:119)
19 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
20 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
21 java.lang.Thread.run(Thread.java:818)

![image](https://user-images.githubusercontent.com/8023129/31077671-fb9bb538-a744-11e7-8ee5-58c2dc0d3967.png)

**Comment by shwenzhang** [comment]
app被禁用网络权限了吧？
