### ISSUE TITLE
在Vivo手机上打了补丁后有异常（使用了databinding）

### ISSUE THREAD

**Issue by renygit** [TinkerPatch/tinkerpatch-sdk#50]
代码用到了databinding，不打补丁没有问题，打了补丁出现了一些异常，但也不是全都异常，很难说明，大致是一个单选按钮组绑定了数据来控制是否可以点击，这部分代码没有任何修改，正常打的包在vivo上没问题，打了补丁就不行了，明明应该能点击的变成不能点击，目前只在vivo上发现这个问题，其它手机上没问题

**Comment by simpleton** [comment]
@renygit 可以贴一下具体出错的log和出错的机型。

**Comment by renygit** [comment]
机型vivo x9，没有错误log，这不是出错。 我现在有几组RadioGroup，每组都是绑定的viewmodel的值来控制enable。
@BindingAdapter("enable")
    public static void setEnabledRadioGroup(RadioGroup rg, boolean enable) {
        for (int i = 0; i < rg.getChildCount(); i++) {
            if(rg.getChildAt(i) instanceof RadioButton) {
                rg.getChildAt(i).setEnabled(enable);
            }else if(rg.getChildAt(i) instanceof ViewGroup){
                setEnabledViewGroup((ViewGroup)rg.getChildAt(i), enable);
            }
        }
    }
<RadioGroup
app:enable="@{viewModel.xxx)}" />
我查看了打补丁后的值没问题，其它手机打了补丁也没这问题，同时enable=true时文字是高亮的，false时文字是灰色的，vivo手机上文字的颜色都对了，就是高亮的RadioGroup的RadioButton不能点击，也就是enable=false了，但是问题是enable=false，文字应该是灰色，可是它是高亮，这到底是什么情况？

**Comment by simpleton** [comment]
可否做一个gif或者小视频说明一下问题。没太理解你的描述，不好意思

**Comment by shwenzhang** [comment]
具体使用的版本是？可以先尝试使用最新的版本，若有资源改变，编译补丁时务必使用apply resource id
