### ISSUE TITLE
exception:java.io.FileNotFoundException: 

### ISSUE THREAD

**Issue by zhencheng11** [TinkerPatch/tinkerpatch-sdk#52]
所有步骤都正确，为何我上传补丁之后，老是出现：exception:java.io.FileNotFoundException；
代码是tinker的项目，我只是修改了appkey而已：
操作步骤：
![image](https://user-images.githubusercontent.com/16297903/32053524-3064af52-ba8e-11e7-9ce5-cb530814d772.png)

1.先调用 TinkerPatch.with().fetchPatchUpdate(true);
log如下：
![image](https://user-images.githubusercontent.com/16297903/32053308-83d7b64e-ba8d-11e7-823b-71240232e2ed.png)

2.再调用 
```
TinkerPatch.with().fetchDynamicConfig(new ConfigRequestCallback() {

                    @Override
                    public void onSuccess(HashMap<String, String> configs) {
                        TinkerLog.w(TAG, "request config success, config:" + configs);
                    }

                    @Override
                    public void onFail(Exception e) {
                        TinkerLog.w(TAG, "request config failed, exception:" + e);
                    }
                }, true);
```
，一直是走onFail()的这个方法，异常信息为：exception:java.io.FileNotFoundException
log如下：
![image](https://user-images.githubusercontent.com/16297903/32053351-abee1402-ba8d-11e7-987d-73ebcbc5f35d.png)
请问这是什么原因，我试了一天了，都是这个样子。

**Comment by simpleton** [comment]
前后台的appversion是否一致？

**Comment by zhencheng11** [comment]
一致的：
这是项目的appVersion
![image](https://user-images.githubusercontent.com/16297903/32083644-d666dcb4-baf6-11e7-96cf-d7e6b37739d9.png)
这是tinker后台的appVertion
![image](https://user-images.githubusercontent.com/16297903/32083662-f0a38be0-baf6-11e7-9dce-cbda68eb4f49.png)
而且后台提示已经下发了，但是请求
 TinkerPatch.with().fetchDynamicConfig()的时候出现
exception:java.io.FileNotFoundException
![image](https://user-images.githubusercontent.com/16297903/32083717-5cada2f8-baf7-11e7-9809-3ecc03ce0dac.png)

**Comment by simpleton** [comment]
Dynamic config是一些动态配置，类似key value的配置。如果不需要可以不用拉取

**Comment by zhencheng11** [comment]
我调用TinkerPatch.with().fetchPatchUpdate(true);的时候，他显示log如下，你帮我看看它请求下来，且修复补丁了吗？因为我杀死程序重启还是没有修复补丁，但是如果我把补丁加入手机本地，然后从本地加载补丁的时候它是可以成功的。难道需要付费了才能真正的上传补丁吗？
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/Tinker.ClientImpl: tinker server sync respond:{"v":2}
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/Tinker.VersionInfo: VersionCheck: patchVersion from 0 to 2
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/Tinker.VersionInfo: GrayGroupCheck: true, gray value:null and my gray value is 7
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/Tinker.ClientImpl: Fetch result: need to update, gray: 7
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/f86d1ff2a47e26bf/3.0.0/file2?d=df691f9d-de82-4f99-9dc8-b90dc940a8da&v=1509067628561, method:GET, body:null
10-27 09:27:08.553 17521-17681/com.tinkerpatch.easy_sample I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-27 09:27:08.623 17521-17681/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
10-27 09:27:08.623 17521-17681/com.tinkerpatch.easy_sample I/Tinker.PatchRequestCallback: TinkerPatchRequestCallback: onPatchUpgrade, file:/data/data/com.tinkerpatch.easy_sample/tinker_server/3.0.0_2.apk, newVersion:2, currentVersion:0
10-27 09:27:08.653 17521-17681/com.tinkerpatch.easy_sample I/Tinker.ServerClient: tinker server report patch download success, patchVersion:2
10-27 09:27:08.663 17521-17681/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://stat.tinkerpatch.com/succ.php, method:POST, body:ch=Null&t=1&sv=1.1.8&pv=2&av=3.0.0&k=f86d1ff2a47e26bf
10-27 09:27:08.663 17521-17681/com.tinkerpatch.easy_sample I/Tinker.VersionInfo: updateVersionInfo file path:/data/data/com.tinkerpatch.easy_sample/tinker_server/f86d1ff2a47e26bf_version.info, appVersion: 3.0.0, uuid:df691f9d-de82-4f99-9dc8-b90dc940a8da, abi:armeabi-v7a, patchVersion:2, patchMd5:1fc233d699142f5f6a58810b14709672, grayValue:7, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
10-27 09:27:08.663 17521-17681/com.tinkerpatch.easy_sample I/Tinker.VersionInfo: updateVersionInfo file path:/data/data/com.tinkerpatch.easy_sample/tinker_server/f86d1ff2a47e26bf_version.info, appVersion: 3.0.0, uuid:df691f9d-de82-4f99-9dc8-b90dc940a8da, abi:armeabi-v7a, patchVersion:2, patchMd5:1fc233d699142f5f6a58810b14709672, grayValue:7, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
10-27 09:27:08.663 17521-17681/com.tinkerpatch.easy_sample I/Tinker.TinkerServerPatchListener: receive a patch file: /data/data/com.tinkerpatch.easy_sample/tinker_server/3.0.0_2.apk, file size:3812
10-27 09:27:08.673 17521-17681/com.tinkerpatch.easy_sample W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
10-27 09:27:08.713 17521-17681/com.tinkerpatch.easy_sample I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-27 09:27:08.713 17521-17681/com.tinkerpatch.easy_sample I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
10-27 09:27:08.823 17521-17681/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
10-27 09:27:08.833 17521-17681/com.tinkerpatch.easy_sample D/Tinker.ClientImpl: [succ] report successfully with url: http://stat.tinkerpatch.com/succ.php, body: ch=Null&t=1&sv=1.1.8&pv=2&av=3.0.0&k=f86d1ff2a47e26bf reportingCount: 0, fail pool size: 0
10-27 09:27:09.183 17521-17521/com.tinkerpatch.easy_sample E/Tinker.ServerClient: tinker server report patch fail, patchVersion:2, errorCode:-243
10-27 09:27:09.203 17521-17521/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://stat.tinkerpatch.com/err.php, method:POST, body:ch=Null&t=1&code=-243&sv=1.1.8&pv=2&av=3.0.0&k=f86d1ff2a47e26bf
10-27 09:27:09.213 17521-17681/com.tinkerpatch.easy_sample I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-27 09:27:09.223 17521-17723/com.tinkerpatch.easy_sample I/Tinker.TinkerServerResultService: receive result: 
                                                                                               PatchResult: 
                                                                                               isSuccess:false
                                                                                               rawPatchFilePath:/data/data/com.tinkerpatch.easy_sample/tinker_server/3.0.0_2.apk
                                                                                               costTime:74
                                                                                               patchVersion:1fc233d699142f5f6a58810b14709672
10-27 09:27:09.223 17521-17723/com.tinkerpatch.easy_sample I/Process: Sending signal. PID: 17689 SIG: 9
10-27 09:27:09.223 17521-17521/com.tinkerpatch.easy_sample I/Tinker.MainActivity: onPatchResult callback here
                                                                                  PatchResult: 
                                                                                  isSuccess:false
                                                                                  rawPatchFilePath:/data/data/com.tinkerpatch.easy_sample/tinker_server/3.0.0_2.apk
                                                                                  costTime:74
                                                                                  patchVersion:1fc233d699142f5f6a58810b14709672
10-27 09:27:09.223 17521-17723/com.tinkerpatch.easy_sample I/Tinker.TinkerServerResultService: wait main handler callback finish
10-27 09:27:09.223 17521-17723/com.tinkerpatch.easy_sample I/Tinker.TinkerServerResultService: handler callback finish had finish, just continue
10-27 09:27:09.223 17521-17723/com.tinkerpatch.easy_sample I/Tinker.TinkerServerResultService: patch fail, please check reason
10-27 09:27:09.313 17521-17681/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
10-27 09:27:09.323 17521-17681/com.tinkerpatch.easy_sample D/Tinker.ClientImpl: [succ] report successfully with url: http://stat.tinkerpatch.com/err.php, body: ch=Null&t=1&code=-243&sv=1.1.8&pv=2&av=3.0.0&k=f86d1ff2a47e26bf reportingCount: 0, fail pool size: 0

**Comment by simpleton** [comment]
不是的，付不付费只和请求量有关。这个-243的错误你其实可以在后台看到错误原因，是因为dex不匹配。
