### ISSUE TITLE
Android Studio3.0兼容

### ISSUE THREAD

**Issue by renygit** [TinkerPatch/tinkerpatch-sdk#53]
希望增加一个兼容Android Studio3.0的版本，不然要报错Error:Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

**Comment by simpleton** [comment]
已经在dev兼容了，近日会发布

**Comment by DreaminginCodeZH** [comment]
请问大概还需要多久发布呢？

**Comment by simpleton** [comment]
如果是调试可以先使用1.2.0 我这边还在做一些测试的工作

**Comment by DreaminginCodeZH** [comment]
好的，发现实际上是忘记一起改 buildScript 的版本了，感谢。
