### ISSUE TITLE
发包的时候，忘记了修改APPversion，怎么办？

### ISSUE THREAD

**Issue by EvanEvil** [TinkerPatch/tinkerpatch-sdk#54]
线上版本是1.2.0，1.3.0增加了一些新的功能，发包的时候，忘记改tinkerpach.gradle里面的APPversion了，还是1.2.0

**Comment by EvanEvil** [comment]
线上1.2.0的用户，直接加载针对1.3.0的补丁应该会有问题吧？不过我项目里,启动后会先检测更新(然后再拉取补丁)，强制更新才能使用，让用户更新到1.3.0，这样的话，我打补丁，APPversion还是写1.2.0 就可以修复1.3.0的APP了吧？

**Comment by simpleton** [comment]
不会，dex会有crc校验
