### ISSUE TITLE
直接打release包可以成功fixed,但是打多渠道包补丁后上传到平台出错

### ISSUE THREAD

**Issue by ncguobiao** [TinkerPatch/tinkerpatch-sdk#55]
![image](https://user-images.githubusercontent.com/20988969/32484109-acfe1806-c3d9-11e7-870a-1a58f4c2566c.png)
![image](https://user-images.githubusercontent.com/20988969/32484130-ba048e0e-c3d9-11e7-93c8-6b9dcbf829c8.png)
![image](https://user-images.githubusercontent.com/20988969/32484134-bfa2aa1c-c3d9-11e7-8fee-e88e056128f4.png)
错误码404，appVersion从平台上拷贝的

**Comment by simpleton** [comment]
多渠道使用的是flavor？如果使用zip comments方式来做多渠道和单包无区别。如果是多flavor需要建立不同的project

**Comment by simpleton** [comment]
是的

**Comment by ncguobiao** [comment]
使用walle呢？感觉文档对这多渠道这块描述的不是很详细，有些懵逼

**Comment by simpleton** [comment]
walle是可以的，算zip comment的方式。就是不需要关心多渠道，只需要维护一个渠道即可
