### ISSUE TITLE
ClassCastException: com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication cannot be cast to Application

### ISSUE THREAD

**Issue by partoftom** [TinkerPatch/tinkerpatch-sdk#56]
Tinker在1.8.0版本上已经修复https://github.com/Tencent/tinker/issues/543 ，请问Tinkerpatch-sdk什么时候尝试升级Tinker版本呢？目前还是1.7.11

**Comment by lazyfatcat** [comment]
TinkerPatch 1.2.1发布了

基于 Tinker 1.9.1
功能: 支持实验功能supportComponent,支持动态新增Activity
功能： 支持android gradle plugin 3.0
Bugfix: 修复Android O patch过程的一个bug
Bugfix: TinkerMultidexConfigTask: FileNotFoundException(manifest_keep.txt)#649
Bugfix: 资源合成时需要保持原来的压缩方式
Bugfix: 修改判断是否为主进程的方式

接入文档： http://tinkerpatch.com/Docs/SDK
更多参考示例： https://github.com/TinkerPatch

**Comment by simpleton** [comment]
Thx @lazyfatcat for answering.
