### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by wwluo14** [TinkerPatch/tinkerpatch-sdk#57]
Unable to create application packageName.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:applicationLike must not be null.

**Comment by simpleton** [comment]
没初始化吧。可以参考 https://github.com/tinkerpatch/tinkerpatch-easy-sample
接入文档： http://tinkerpatch.com/Docs/SDK
