### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by ErQi** [TinkerPatch/tinkerpatch-sdk#59]
gradle插件更新到3.0.0之后,修改完补丁版本号之后无法打包,提示无法修改mainfest文件

**Comment by simpleton** [comment]
请升级到最新的1.2.1

**Comment by ErQi** [comment]
就是最新的1.2.1版本,不修改appVersion,与基准包一样可以打出补丁包,修改之后就提示无法修改,打包失败.
https://github.com/Tencent/tinker/issues/671
这里似乎也有人提出了类似的问题

**Comment by simpleton** [comment]
可以先按那个issue里的方法workaround，已经在dev修复了，下次发布会带上

**Comment by SimpleGentleman** [comment]
@simpleton 你好
1-----4. 向后台请求补丁升级配置
向后台获取是否有补丁包更新,默认的访问间隔为3个小时,若参数immediately为 true,即每次调用都会真正的访问后台是否有更新。
TinkerPatch.with().fetchPatchUpdate(false)；

2-----5. 向后台请求在线参数配置
向后台请求在线参数配置，默认的访问间隔为3个小时, 若参数 immediately 为 true, 即每次调用都会真正的访问后台是否有更新。
TinkerPatch.with().fetchDynamicConfig(false)；

上面1与2的区别在哪里?我的理解如下:
前者是说:有无最新的补丁包
后者的意思:是不管当前有无最新补丁包,是查询配置(比如条件下发,灰度下发),更新后还是会间隔下载补丁包,但是按照新更改的配置条件修复bug;补丁包的下载照前.  
是这样理解吧?

**Comment by simpleton** [comment]
是的，是2个独立的请求
