### ISSUE TITLE
使用Dexguard混淆后，无法打补丁

### ISSUE THREAD

**Issue by neuyu** [TinkerPatch/tinkerpatch-sdk#61]
插件版本 ：classpath "com.tinkerpatch.sdk:tinkerpatch-gradle-plugin:1.2.1"
Dexguard版本： 8.0.0
gradle版本：3.1

生成基准包时，在bakApk中无法找到mapping文件，需要手动拷入。
针对少量文件修改，打补丁包时，需要设置ignoreWarning = true 以及supportComponent = true，
但仍然出现large modify resource: resources.arsc 在dexguard配置中，已经加上

-keepresources **
-keepresourcefiles res/mipmap-*/*
-keepresourcefiles res/**
-keepresourcefiles AndroidManifest.xml

无混淆时，查看res_log等一切正常

**Comment by simpleton** [comment]
不好意思，闭源产品，暂时无法兼容
