### ISSUE TITLE
上传补丁包之后，没有下载

### ISSUE THREAD

**Issue by ZHJ-30** [TinkerPatch/tinkerpatch-sdk#65]
上传补丁后重启应用，没有下载也没有提示

**Comment by simpleton** [comment]
Sdk 设计本来就没有提示，只能查看log

**Comment by haohongxian77** [comment]
// 获取当前的补丁版本
            AppLogger.d("Current patch version is " + TinkerPatch.with().getPatchVersion());
这个是本地的吧应该，然后我安装步骤大了base和patch包，上传之后也是一直没有下载下来，重启了都不好使....

**Comment by ZHJ-30** [comment]
我的是由于使用了API23但没有动态申请读写文件权限，导致下载不成功。加载权限申请就好了

**Comment by haohongxian77** [comment]
我的是4.4.2的，不用有读写权限啊...,使用的是最新版本的tinker
