### ISSUE TITLE
你们的网站崩了

### ISSUE THREAD

**Issue by 471448446** [TinkerPatch/tinkerpatch-sdk#66]
_STORAGE_WRITE_ERROR_:./Application/Runtime/Cache/Home/ccea6a400660ce54d68cab67b9f68781.php
错误位置
FILE: /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Storage/Driver/File.class.php 　LINE: 48

TRACE
#0 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Storage/Driver/File.class.php(48): E('_STORAGE_WRITE_...')
#1 [internal function]: Think\Storage\Driver\File->put('./Application/R...', ' #2 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Storage.class.php(37): call_user_func_array(Array, Array)
#3 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Template.class.php(114): Think\Storage::__callstatic('put', Array)
#4 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Template.class.php(114): Think\Storage::put('./Application/R...', ' #5 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Template.class.php(76): Think\Template->loadTemplate('./Application/H...', '')
#6 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Behavior/ParseTemplateBehavior.class.php(32): Think\Template->fetch('./Application/H...', Array, '')
#7 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Hook.class.php(119): Behavior\ParseTemplateBehavior->run(Array)
#8 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Hook.class.php(89): Think\Hook::exec('Behavior\\ParseT...', 'view_parse', Array)
#9 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/View.class.php(126): Think\Hook::listen('view_parse', Array)
#10 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/View.class.php(72): Think\View->fetch('', '', '')
#11 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Controller.class.php(56): Think\View->display('', '', '', '', '')
#12 /data/home/bxu2340890104/htdocs/Application/Home/Controller/IndexController.class.php(148): Think\Controller->display()
#13 [internal function]: Home\Controller\IndexController->login()
#14 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/App.class.php(164): ReflectionMethod->invoke(Object(Home\Controller\IndexController))
#15 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/App.class.php(202): Think\App::exec()
#16 /data/home/bxu2340890104/htdocs/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#17 /data/home/bxu2340890104/htdocs/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#18 /data/home/bxu2340890104/htdocs/index.php(32): require('/data/home/bxu2...')
#19 {main}

**Comment by simpleton** [comment]
多谢提醒，当时已经修复了。
