### ISSUE TITLE
patch未被下载，这是啥原因

### ISSUE THREAD

**Issue by haohongxian77** [TinkerPatch/tinkerpatch-sdk#67]
云端
App版本号：1.0.0
当前补丁版本号：4
本地
app/build.gradle 
versionCode 10000000
 versionName "1.0.0"

tinkerpatch.gradle
/** 注意: 若发布新的全量包, appVersion一定要更新 **/
    appVersion = "1.0.0"

上传patch之后没有下载啊

**Comment by haohongxian77** [comment]
不清楚是什么原因在5版本的手机上可以，但是在4版本的盒子上不行....

**Comment by haohongxian77** [comment]
这个上传之后热更新下载啥的会有延迟吗？！有的话大概是多少....

**Comment by simpleton** [comment]
@haohongxian77 如果本地debug可以安装debugtools，http://tinkerpatch.com/Docs/dev。
模式轮训的请求会有3小时间隔，如果想要试试生效，可以配合push通道。
```
     // 每隔3个小时(通过setFetchPatchIntervalByHours设置)去访问后台时候有更新,通过handler实现轮训的效果
        TinkerPatch.with().fetchPatchUpdateAndPollWithInterval();
```
