### ISSUE TITLE
屏幕锁屏 app就crash

### ISSUE THREAD

**Issue by FrameJack** [TinkerPatch/tinkerpatch-sdk#7]
11-28 14:51:05.999 17597-17597/com.cdyzrs.golf E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
11-28 14:51:07.059 17693-17693/com.cdyzrs.golf:channel E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
11-28 14:51:09.889 17597-17930/com.cdyzrs.golf E/Tinker.ClientImpl: tinker server sync respond:{"e":1}

手机型号 三星 9006

E/Tinker.SampleUncaughtExHandler: uncaughtException:Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

**Comment by shwenzhang** [comment]
请给完整日志！

**Comment by simpleton** [comment]
日志不全，等待补充完整日志，这里先关闭了。
PS： 可以尝试下 `com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.0.1`的一键集成版本。
