### ISSUE TITLE
是不是要等到设置的间隔查询时间才会更新

### ISSUE THREAD

**Issue by tmyzh13** [TinkerPatch/tinkerpatch-sdk#70]
.setFetchPatchIntervalByHours(3); 按照流程提交补丁之后再次重启app没有即使更新

**Comment by simpleton** [comment]
线上环境是的。本地debug的时候可以通过安装debugtools来避免这个时间间隔。http://tinkerpatch.com/Docs/dev

**Comment by tmyzh13** [comment]
三个小时之后重启应用  热修复的内容没有出现 可能有哪些原因  variantName = "release"  baskInfo 修改成了 assembleRelease打包之后对应的包信息  然后用tinkerPatchRelease打包之后 output --release 里面取的patch_signed_7zip.apk做的补丁包信息

**Comment by simpleton** [comment]
看具体log 吧

**Comment by tmyzh13** [comment]
感谢您的回复 
看到一些提示 似乎是配置不对 导致下载补丁失败
03-06 14:50:42.665 30630-30630/com.example.issuser.myapplication I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/52ef2fe7025c9bd3/1.0.1?d=53f97ebe-cd91-42ec-b775-488f3e9db5a0&v=1520319042665, method:GET, body:null
03-06 14:50:42.931 30630-30681/com.example.issuser.myapplication I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
03-06 14:50:42.931 30630-30681/com.example.issuser.myapplication W/Tinker.PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/52ef2fe7025c9bd3/1.0.1?d=53f97ebe-cd91-42ec-b775-488f3e9db5a0&v=1520319042665
03-06 14:50:42.931 30630-30681/com.example.issuser.myapplication E/Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com
1 在生成补丁报的时候，要不要保证当前包的appVersion一致 也就是打一次补丁的old 和new apk tinkerpatch.gradle appVersion 一直
2管理平台上的新增项目名称是否与实际项目名称一致
3appkey 我就是点开我新增项目之后看到的appkey信息

**Comment by simpleton** [comment]
1.需要保持一致
2.项目名只是方便你管理
3.是的

**Comment by tmyzh13** [comment]
将上面三点检查过之后 还是不成功  能否帮我看一下log 里面有一些fail 我不清楚是怎么产生的
03-06 16:39:12.360 8057-8057/com.example.issuser.myapplication W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.example.issuser.myapplication/tinker
03-06 16:39:12.361 8057-8057/com.example.issuser.myapplication I/Tinker.ReflectApp: with app application from manifest applicationName:com.example.issuser.myapplication.App
03-06 16:39:12.361 8057-8057/com.example.issuser.myapplication I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 16:39:12.364 8057-8057/com.example.issuser.myapplication I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 16:39:12.366 8057-8057/com.example.issuser.myapplication I/Tinker.ServerUtils: with app key from manifest appKey:52ef2fe7025c9bd3
03-06 16:39:12.366 8057-8057/com.example.issuser.myapplication I/Tinker.ServerUtils: with app version from manifest appVersion:1.0.0
03-06 16:39:12.368 8057-8057/com.example.issuser.myapplication I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.example.issuser.myapplication/tinker_server/52ef2fe7025c9bd3_version.info, appVersion: 1.0.0, uuid:b3e4dce9-8320-4695-af94-863f7ddc49a8, abi:arm64-v8a, patchVersion:0, patchMd5:, grayValue:6, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 16:39:12.369 8057-8057/com.example.issuser.myapplication I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 1.0.0, appKey: 52ef2fe7025c9bd3
03-06 16:39:12.372 8057-8057/com.example.issuser.myapplication W/Tinker.Tinker: tinker patch directory: /data/user/0/com.example.issuser.myapplication/tinker
03-06 16:39:12.372 8057-8057/com.example.issuser.myapplication I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 16:39:12.373 8057-8057/com.example.issuser.myapplication I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.example.issuser.myapplication, main process:true, systemOTA:false, fingerPrint:HONOR/STF-AL00/HWSTF:7.0/HUAWEISTF-AL00/C00B201:user/release-keys, oatDir:null, useInterpretMode:false
03-06 16:39:12.373 8057-8057/com.example.issuser.myapplication W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 16:39:12.373 8057-8057/com.example.issuser.myapplication I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.example.issuser.myapplication/tinker, code: -2, cost: 2ms
03-06 16:39:12.373 8057-8057/com.example.issuser.myapplication W/Tinker.Tinker: tinker load fail!
03-06 16:39:12.373 8057-8057/com.example.issuser.myapplication I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 16:39:12.433 8057-8057/com.example.issuser.myapplication I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 3600000
03-06 16:39:12.482 8057-8057/com.example.issuser.myapplication W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
03-06 16:39:12.483 8057-8057/com.example.issuser.myapplication W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
03-06 16:39:12.483 8057-8057/com.example.issuser.myapplication I/Tinker.ServerClient: tinker sync should wait interval 3246s

**Comment by tmyzh13** [comment]
谢谢  已经可以了  似乎是管理平台的app写版本的时候与程序里面的不一致
