### ISSUE TITLE
Vivo X20A(Android25) patch -203 错误

### ISSUE THREAD

**Issue by kunsir6** [TinkerPatch/tinkerpatch-sdk#71]
对比进行：
（1）小米5s Plus(Android 24) 多次patch成功。

（2）Vivo X20A(Android25) 多次patch，均是 -203 错误。

**Comment by kunsir6** [comment]
用了锤子的手机，也是Android25的，patch也是成功的。看来跟os版本无关。

**Comment by simpleton** [comment]
-203 | 补丁合成dexopt文件不存在
你可以尝试用一台非vivo的手机测试下，这个问题是因为vivo oppo部分机型的dex2oat是异步进行的，最终可以达到合成成功的状态，但存在一个gap，访问会报-203
