### ISSUE TITLE
patch只要上传了，每次都下载。responseCode=200，太浪费流量了吧

### ISSUE THREAD

**Issue by kunsir6** [TinkerPatch/tinkerpatch-sdk#72]
I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/e54f6bebbc9c1ee2/t2000?d=2a7e0af6-fc3d-44aa-8b21-46fe65dca0d4&v=1520480826553, method:GET, body:null
I/Tinker.UrlConnectionFetcher: response code 200 msg: OK

patch只要上传了，每次都下载。responseCode=200，太浪费流量了吧。走http的304协议，如果包没有改变，就走304协议，应该能省不少流量。

**Comment by simpleton** [comment]
这个url存的不是patch文件本身，是一个配置信息。非常的小
